Update cpp-linter.yml

diff --git a/.github/workflows/cpp-linter.yml b/.github/workflows/cpp-linter.yml
--- a/.github/workflows/cpp-linter.yml
+++ b/.github/workflows/cpp-linter.yml
@@ -16,8 +16,8 @@ jobs:
           files-changed-only: false
 
       - name: Fail fast?!
-        if: steps.linter.outputs.checks-failed > 0
-        run: echo "Some files failed the linting checks!"
+        #if: steps.linter.outputs.checks-failed > 0
+        #run: echo "Some files failed the linting checks!"
         # for actual deployment
-        # run: exit 1
+        run: exit 1
         
